services:
  - type: web
    name: ortho-fracture-detector
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app/app.py
    envVars:
      - key: FLASK_ENV
        value: production
