services:
  - type: web
    name: ortho-trace
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app/app.py"
    envVars:
      - key: FLASK_ENV
        value: production
